### ISSUE TITLE
NoClassDefFoundError NexusSocket

### ISSUE THREAD

**Issue by trevjonez** [jfsso/intercom-android-slim#1]
Trying to run the slim aar i run into the following error

```
java.lang.NoClassDefFoundError: io.intercom.android.sdk.nexus.NexusSocket
      at io.intercom.android.sdk.nexus.NexusClient.connect(NexusClient.java:37)
      at io.intercom.android.sdk.NexusWrapper.connect(NexusWrapper.java:19)
      at io.intercom.android.sdk.lifecycles.Lifecycles.onActivityStarted(Lifecycles.java:96)
      at android.app.Application.dispatchActivityStarted(Application.java:223)
      at android.app.Activity.onStart(Activity.java:1245)
      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234)
      at android.app.Activity.performStart(Activity.java:6329)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2675)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2777)
      at android.app.ActivityThread.access$900(ActivityThread.java:179)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:145)
      at android.app.ActivityThread.main(ActivityThread.java:5972)
      at java.lang.reflect.Method.invoke(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:372)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

Gradle 2.6 with the 1.5.0 android gradle plugin. based on reviewing the --info output of the build, nothing seems wrong and reviewing the output dex file for count shows all of the Classes in the correct place.

I've tried both pulling it down from our private maven server as well as just adding it as an aar module to the build in an attempt to ensure it wasn't related to the non standard way I was posting it to the maven server.

My main thought right now is it may be an issue with the 1.5.0 plugin's new task system.

**Comment by jfsso** [comment]
@trevjonez I've been using it with 1.5.0 plugin and Gradle 2.6 without problems so far. What I can think of is that classes aren't loaded when an import is missing, so it can be that one or more dependencies are missing. Do you have these declared on your dependencies in build.gradle?

```
compile 'com.squareup.okio:okio:1.6.0'
compile 'com.squareup.okhttp:okhttp:2.5.0'
compile 'com.squareup.okhttp:okhttp-ws:2.5.0'
```

**Comment by trevjonez** [comment]
I think I missed the okhttp-ws package on my last attempt. I will retry today and get back.

**Comment by trevjonez** [comment]
Sorry for the delay. It was my fault on the crash I missed the okhttp-ws all is well now.
